name: ScanCentral SAST Scan

on: [workflow_dispatch]

jobs:
  ScanCentral-SAST-Scan:
    runs-on: ubuntu-latest

      steps:
      - name: Check out source code
        uses: actions/checkout@v4  
      - name: Run ScanCentral SAST Scan
        uses: fortify/github-action@v1
        with:
          sast-scan: true
        env:
          SSC_URL: ${{secrets.SSC_URL}}
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          SC_SAST_CLIENT_AUTH_TOKEN: ${{secrets.CLIENT_AUTH_TOKEN}}
          # EXTRA_SC_SAST_LOGIN_OPTS: --socket-timeout=60s
          SSC_APPVERSION: 8ball:1
          # EXTRA_PACKAGE_OPTS: -bf custom-pom.xml
          # DO_WAIT: true
          # DO_EXPORT: true
