name: ScanCentral SAST Scan

on: [workflow_dispatch]

jobs:
  ScanCentral-SAST-Scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: fortify/gha-setup-scancentral-client@v2
        with:
          client-auth-token: b8f28277-eca4-40dd-afa4-d0cf3c911288
      - run: scancentral -url http://b8d00bd32ecb.sn.mynetname.net:8080/ssc start -bt none
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: scancentral-logs
          path: ~/.fortify/scancentral/log
